### PR TITLE
Implementation of simplifyArithmeticBody method in SubsumptionT…

### PR DESCRIPTION
**Pull request by feliciahalim**
This is an early implementation of simplifyArithmeticBody method in SubsumptionTableEntry. Please review the implementation. If you are happy with this implementation, I will create the generalized version of it. Otherwise, I will be happy for feedback. Thank you.

### CODE REVIEW

**Comment by domainexpert** [comment]
Awesome! Just a few things:

1. Please use camel casing, e.g., `equationFull` instead of `equation_full`.
2. You could simply return the newly-created body at Line 157 of `ITree.cpp` as it no longer has quantified variable, and then remove Lines 158-161.
3. In creating new body at Line 157, you may want to use `::alloc` instead of `::create`, as `::create` often does more things, so here I suggest replacing, for example,  `SleExpr::create` with `SleExpr::alloc`.
4. After staging the files using `git add --all` for commit, but before committing, please run `git clang-format` to standardize the code format. In case git changes some files, please re-stage those using `git add --all` and so on until there is no more change, then you can commit.

I'm noticing we're getting back the subsumptions for `addition_safe1.c`. Good job!

**Comment by feliciahalim** [comment]
Update 7c5a4cf contains:

1. Generalize simplified arithmetic body implementation by creating a new method in Expr.cpp which able to produce a new expression from kind of operation and vector of expressions. 
2. Use camel casing 
3. Return the simplified version directly because it is no longer has quantified variable 
4. Use Alloc instead of previously Create method

**Comment by domainexpert** [comment]
@feliciahalim `createFromKindVer2` replicates the functionality of `createFromKind`. There can be a problem here as someone who modifies `createFromKind` would always have to modify `createFromKindVer2` as well. I suggest:
1. Reimplement `ceateFromKindVer2` using a call to `createFromKind`.
2. Rename `createFromKindVer2` into a name that is more descriptive: `Ver2` does not explain much.
3. Test your procedure with more examples by adding more test examples with more conditions in the interpolant and more variables involved in the conditions. Please push these new test examples that you will create to `feliciahalim/klee-examples/basic`.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for the suggestion. I have removed createFromKindVer2. In the current implementation,  ref<Expr> is wrapped in the CreateArg, so that it is able to use the original method createFromKind. I will also keep testing the implementation with more examples.

**Comment by domainexpert** [comment]
Copied from #27 's message: The implementation of the simplifier is applicable only for limited cases currently, so I have added several if conditions in the methods' body to check for the conditions under which it is applicable. I think it is still important to develop tests for this procedure, as the conditions may not capture all cases where it is not applicable.

**Comment by feliciahalim** [comment]
@domainexpert  In the commit c3f6e85, I have added a function to simplify equality expression and handling many interpolant and 1 equality.

**Comment by domainexpert** [comment]
@feliciahalim Do you have example(s) where the new simplification procedure is triggered? Would you please add those to feliciahalim/klee-examples? Thank you in advance.

**Comment by domainexpert** [comment]
It seems to run correctly on `loop_safe.c`. Still need to test if it runs correctly on feliciahalim/klee-examples basic examples. It currently fails on `addition_safe6.c`.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for the feedback. It currently fails on `addition_safe6.c` because it uses disjunction while we only support for conjuction.  `addition_safe6.c` code looks very similar with `addition_safe5.c.` Would you please explain why it uses disjunction instead of conjunction?

**Comment by domainexpert** [comment]
I have moved `Expr::createFromKind` for binary to `SubsumptionTableEntry::createBinaryOfSameKind` so that our changes as much as possible will be independent to KLEE source, this is so that our changes can be easily merged with KLEE later. The only two remaining main issues in this PR are indicated in the two FIXME comments in `ITree.cpp`, namely:

1. Currently we handle only single clause of the equality constraints. We should handle general DNF in the future.
2. In addition, we also currently only handle one-assignment clause: We only perform substitution using a single equality and one or many interpolants. We should instead use all equalities given a clause.

**Comment by domainexpert** [comment]
@feliciahalim Correction: Equality constraints are actually in CNF and not DNF. First option is to convert CNF to DNF, and use each conjunctive clause for simplifying interpolant. Unfortunately, converting CNF to DNF is an operation with time exponential in the size of the formula. So, in 7064df8 at present we collect only atomic equality clauses of the CNF (i.e., clause ci which are atomic equalities A==B, for 1<=i<=n, of the equality constraint CNF c1 /\ ... /\ cn) in the `interpolantPack` for simplifying the interpolant. The only remaining issue now is indicated in the only FIXME comment left in `SubsumptionTableEntry::simplifyArithmeticBody`, which is to use all equalities in `interpolantPack` for simplifying the interpolant.

**Comment by feliciahalim** [comment]
@domainexpert  I have improved the algorithm which enable usage of all equalities for simplifying the interpolant. https://github.com/feliciahalim/klee-examples/commit/cf4a0974ea4e9218d93167af40f6b015e281f2fe example can be used to show the new many-to-many interpolant(s) equalities simplification. It able to do 2 subsumptions, however there's some cases where there's no `shadow_expression = non_shadow_expression` equality expression and thus interpolant cannot be further simplified.

**Comment by domainexpert** [comment]
I have corrected the logic in `SubsumptionTableEntry::simplifyArithmeticBody`. Please have a look. I also added elaborate comments. I think what you meant in your comment before that "there is no `shadow expression = non_shadow_expression`" is more accurately the problem that it seems at a glance difficult to specify shadow variables as functions of non-shadow variables. To solve this issue, we may need to employ elimination, such as Fourier-Motzkin, although this may not be sound in bitvector domain. But more important problem is that at present there are cases where the solver could not decide (in-)validity with `addition_safe8.c`, even when quantifiers have been removed. This should be investigated first.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for added elaborate comments.  I have modified the substitution process in simplifyArithmeticBody, which can be seen in https://github.com/feliciahalim/klee/commit/7332076324db3964be23d752c0046942ccfe7cea . This modified version is much more simple than previous iterative version.

**Comment by domainexpert** [comment]
@feliciahalim Thanks, but my question is what with that AddExpr at Line 254 of ITree.cpp? Why only AddExpr? Can your procedure handle other expressions as well?

**Pull request merged**
