### PR TITLE
 Bug fix on break to outer loop in SubsumptionTableEntry::subsumed by using goto

### PR DESCRIPTION
**Pull request by feliciahalim**
Bug fix on break to outer loop in SubsumptionTableEntry::subsumed by using goto, otherwise it has buggy iteration movement which happens in tr_small example

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim Awesome! But perhaps this is not ready to be merged yet as it still has debug logs. Also, are you sure there is no way other than using goto? Perhaps we could use a boolean flag instead?

**Comment by domainexpert** [comment]
@feliciahalim Could you please also try to remove the checks at Lines 1241-1244 to see if we could still run tr_small? Perhaps the problem that was temporarily fixed by those lines were caused by the outer loop not exited properly.

**Comment by feliciahalim** [comment]
@domainexpert It able to run successfully after removing the check at Lines 1241-1244. To answer your first question, Boolean flag is also possible, but goto seems more straightforward to indicate that we would like to break the loops. If you are happy with this, I will clean up the debug logs, so it is easier to do merging.

**Comment by domainexpert** [comment]
@feliciahalim Ok, let's allow `goto`, although it's against common beliefs. Please go ahead removing the logs and push another commit.

**Comment by feliciahalim** [comment]
@domainexpert I have removed the logs and please let me know if this version is ready to be merged. Thanks

**Comment by domainexpert** [comment]
Merged it. Well done!

**Pull request merged**
