### PR TITLE
Bugfix: load value from pointer

### PR DESCRIPTION
**Pull request by feliciahalim**
@domainexpert  Fixing bug of load value from the pointer, specifically to fix the problem in https://github.com/feliciahalim/klee-examples/blob/master/basic/argument2.c

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim It seems the whole of file lib/Core/Dependency.cpp has been clang-formatted after update. Would you please tell me which lines have changed?

**Comment by domainexpert** [comment]
@feliciahalim Would you also please rename argument.c to argument1.c in klee-examples/basic?  Just for uniformity.

**Comment by domainexpert** [comment]
@feliciahalim It seems the comment in the example klee-examples/basic/argument2.c is incorrect. Would you please correct it?

**Comment by feliciahalim** [comment]
@domainexpert 685-691 lines have changed. I also modify a variable name in previous lines 670-679 for uniformity.

**Comment by feliciahalim** [comment]
@domainexpert I have renamed to argument1.c and removed the comment in argument2.c.

**Comment by domainexpert** [comment]
@feliciahalim Would you please merge with master and push the result?
```
git checkout bugfix
git merge master
push -u origin bugfix
```
This will merge Binh's commit from yesterday.

**Comment by feliciahalim** [comment]
@domainexpert I have merged them, details in : 	fd299af

**Comment by domainexpert** [comment]
@feliciahalim Thank you! In the latest commit I've made the main function argument load turned into an allocation when abstractly executing load instruction in Dependency::execute. This is more conforming to the previous revisions as environment variables are handled similarly at the same location in the previous revisions. Please check and merge if you think it's fine.

**Comment by feliciahalim** [comment]
@domainexpert It looks fine for me. I have merged them.

**Pull request merged**
